# C:\Users\xiaoju\Desktop\eloft-pipei\cross_matching\config\default_config.yml

# 路径配置
paths:
  # EfficientLoFTR 代码库路径
  eloft_root: "C:/Users/xiaoju/Desktop/eloft-pipei/EfficientLoFTR-main"
  # 模型权重路径
  model_weights: "C:/Users/xiaoju/Desktop/eloft-pipei/EfficientLoFTR-main/weights/eloftr_outdoor.ckpt"
  # 基准图路径
  base_image: "0_jizhun/BASE.tif"
  # 实时图像文件夹
  realtime_dir: "1_input/"
  # 输出结果路径
  output_csv: "2_output/image_info.csv"
  output_debug_dir: "2_output/debug_images/"

# 相机与飞行参数
camera:
  fov: 75.0          # 视场角 (度)
  aspect_ratio: [4, 3] 
  resolution: [640, 480] 

# 初始导航状态 (根据 DJI_0149.JPG 的实际位置微调)
initial_state:
  lng_o: 108.757612  # 108.7560168
  lat_o: 34.14962169 # 34.14985025
  h_o: 500.0         # 飞行相对高度
  beta_o: -53.3      # 初始航向角
  h0: 0.0            # 起飞点地面高度

# 匹配算法参数
matcher:
  conf_threshold: 0.2 # 降低门槛以提高召回
  ransac_threshold: 4.0
  mag_k: 1.1         # 搜索区域扩大系数
  fine_temperature: 10.0 # 新增：精细匹配温度系数，强制设为 10.0
  # 校验单应性矩阵的尺度范围 (a, b)，由于无人机高度变化，放宽至 0.5-1.5
  #scale_q: 0.2       # 尺度校验阈值因子
  valid_k: [0.5, 1.5] # 默认有效单应性变换系数 (a, b)[0.8, 1.2]
